export const botInterface = {
  en: {
    buttons: {
      main: ['add activity', 'track time', 'statistics', 'settings'],
      settings: ['change language', 'change name'],
      initial: ['register'],
      statics: ['today', 'this week', 'whole time', 'main business'],
      stop: ['stop'],
      cancel: ['cancel'],
    },
    messages: {
      hello: 'hellow',
      canceled: 'canceled',
      trackTime: 'choose the activity',
      addActivity: 'type new activity',
      pickLanguage: 'choose language from the list',
      sendYourName: 'send your name',
      activityExists: 'such activity type already exists',
      shouldBeRegistered: 'you should be registered to perform the query',
      activitiesListSent: 'here is your activities list',
      startedTrackActivity: 'started track activity: ',
      youHaveNoActivitiesYet: `you have no activities yet, you can add them through the button 'add activity' in main menu`,
      successfullyRegistered: 'successfully registered',
      alreadyInProgressActivity: 'already in progress another activity tracking, finish previous before start new one',
      successfullyAddedActivity: 'activity type successfully added',
      activityRecorded: (activity: string) => `activity ${activity} recorded, waiting for impression about the activity`,
      timeElapsedSinceStart: (time: string) => `activity duration time: ${time}`,
      activityImpressionRecorded: 'activity impression recorded, waiting for new activities to track',
      settingsMessage: 'what would you like to change?',
      languageChanged: 'successfully changed language',
      pickStatType: 'which type of stat are you interested in?',
      activityName: 'title',
      activityDuration: 'time',
      activityImpression: 'impression',
    },
  },
  ua: {
    buttons: {
      main: ['додати активність', 'відстежувати час', 'статистика', 'налаштування'],
      settings: ['змінити мову', 'змінити імʼя'],
      initial: ['зареєструватися'],
      statics: ['сьогодні', 'на цьому тижні', 'повна', 'улюблена справа'],
      stop: ['зупинити'],
      cancel: ['скасувати'],
    },
    messages: {
      hello: 'добридень, зареєструйтеся будь ласка',
      canceled: 'скасовано',
      trackTime: 'оберіть вид діяльності',
      addActivity: 'впишіть нову активність',
      sendYourName: 'відправте своє імʼя',
      pickLanguage: 'обери мову зі списку',
      activityExists: 'такий тип активності вже присутній у вашому профілі',
      activityRecorded: (activity: string) => `діяльність ${activity} записана, очікую ваших вражень від діяльності`,
      timeElapsedSinceStart: (time: string) => `час вибраної активності: ${time}`,
      shouldBeRegistered: 'ви повинні бути зареєстровані для цієї дії',
      activitiesListSent: 'ось ваш список активностей',
      startedTrackActivity: 'почав відслідковувати: ',
      successfullyRegistered: 'успішно зареєстровані у боті',
      youHaveNoActivitiesYet: `у вас ще немає активностей для відслідковування, але ви можете додати їх за допомогою кнопки 'додати активність' у головному меню`,
      alreadyInProgressActivity: 'ви вже відслідковуєте активність, завершіть попередню перед початком нової',
      successfullyAddedActivity: 'новий тип активності додано',
      activityImpressionRecorded: 'враження про активність записане, чекаю на нові активності для відслідковування',
      settingsMessage: 'що б ви хотіли змінити?',
      languageChanged: 'мову успішно змінено',
      pickStatType: 'яка статистика вас цікавить?',
      activityName: 'назва',
      activityDuration: 'час',
      activityImpression: 'враження',
    },
  },
  languages: ['en', 'ua'],
}

export const messageTypes = {
  // @ts-ignore
  register: botInterface.languages.map((lang: string) => botInterface[lang].buttons.initial[0]),
}
